using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Unit : MonoBehaviour
{
    public UnitData data;
    public SpriteRenderer myRenderer;
    public string unitID = "";

    private void Start()
    {
        bool autoGenerated = false;
        if (data == null) { Debug.Log("generating new data"); autoGenerated = true; data = ScriptableObject.CreateInstance<UnitData>(); }
        if (myRenderer == null) return;

        if(autoGenerated)
        {
            if (Random.Range(0, 3) == 1)
            {
                data.controlledByPlayer = false;
            }
        }

        if (data.controlledByPlayer)
            myRenderer.color = Color.blue;
        else
            myRenderer.color = Color.red;

    }
}
